### PR TITLE
Make event sink lock retry numbers configurable

### PR DESCRIPTION
**Pull request by twe4ked**
We're hitting some of these errors while creating large numbers of events. Let's make them configurable so we can easily play with the numbers to see what works.

I'm not touching the defaults but they're almost certainly not what we want, I think something more like:

```
LOCK_RETRY_COUNT = 10
LOCK_RETRY_SLEEP = 0.5
```

Would make more sense as a default. This is also something that could be configured very differently for a web process compared with a background process.

### CODE REVIEW

**Review by charithperera — APPROVED** [review]
Do we have specs for this kind of stuff? Guessing probably not

**Comment by twe4ked** [comment]
There are some existing specs making sure that the retry functionality works. I decided against adding tests to ensure we can override the values as I don't think they'll add much value. WDYT?

**Review by amanda08 — APPROVED** [review]
👍  Making them configurable will help us figure out the right defaults.

**Comment by charithperera** [comment]
> There are some existing specs making sure that the retry functionality works. I decided against adding tests to ensure we can override the values as I don't think they'll add much value. WDYT?

Yeah thats fair. If this broke anything the existing specs would have broken.

**Pull request merged**
