### PR TITLE
Bundle update

### PR DESCRIPTION
**Pull request by twe4ked**
Few questions too:

- We currently have a few development dependencies listed in the `gemspec`, and a few in the `Gemfile`. What should we use?
- Should we commit the `Gemfile.lock`? I'm thinking yes, as it gives us a known state for development.

### CODE REVIEW

**Comment by timriley** [comment]
@twe4ked I think we should actually remove the Gemfile.lock from source control. That's the established convention for gems.

[Here's why](https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/), in a long-ago post from Yehuda Katz:

> **Do not check your Gemfile.lock into version control,** since it enforces precision that does not exist in the gem command, which is used to install gems in practice. Even if the precision could be enforced, you wouldn't want it, since it would prevent people from using your library with versions of its dependencies that are different from the ones you used to develop the gem.

FWIW, this is the same approach we follow across all the gems I help maintain.

**Comment by twe4ked** [comment]
Sweet, sounds good to me. I should have had a bit of a Google on that one 😅

**Comment by timriley** [comment]
As for development dependencies, it's really a "neither here nor there" kind of thing at its root. Either works, but I reckon putting them all in the `Gemfile` is probably the best thing to do, since it gives us a few niceties that you don't get from the gemspec (e.g. having separate groups, which you sometimes use for e.g. providing gems for your benchmarks only)

**Comment by twe4ked** [comment]
Remove `Gemfile.lock` https://github.com/cultureamp/event_framework/pull/12

Just checked, and we've only got development gems in the Gemfile, so we're good there.

**Pull request closed without merging**
